Django/django_course/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"
urlpatterns = [
    path("", views.index, name="index"),
    path("detail/<int:pk>/", views.blog_detail, name="blog_detail"),
    path("create/", views.create_blog, name='create_blog'),
    path("update/<int:pk>/", views.update_blog, name='update_blog'),
    path('contacts/', views.contacts, name='contacts'),
]

Django/django_course/django_course/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("blog.urls"), name="blog"),
    path("users/", include("users.urls"), name="users"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django/django_course/users/urls.py
from django.urls import path
from . import views

app_name="users"
urlpatterns = [
    path("login/", views.Login.as_view(), name="login"),
    path("logout/", views.Logout.as_view(), name="logout"),
    path("register/", views.register, name="register"),
]

Django/django_course/blog/models.py
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Blog(models.Model):
    title = models.CharField(max_length=200, verbose_name="Заголовок")
    content = models.TextField(verbose_name="Содержание")
    date_published = models.DateTimeField(default=timezone.now, verbose_name="Дата публикации")
    image = models.ImageField(upload_to="images/", verbose_name="Изображение")
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Автор", null=True, blank=True)

    def __str__(self):
        return str(self.title)
    
    def get_absolute_url(self):
        return reverse("blog:blog_detail", kwargs={"pk": self.pk})
    
    class Meta:
        verbose_name = "Блог"
        verbose_name_plural = "Блоги"

class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, verbose_name="Блог")
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Автор", null=True, blank=True)
    date_published = models.DateTimeField(default=timezone.now, verbose_name="Дата публикации")
    text = models.TextField(verbose_name="Текст комментария")

    def __str__(self):
        return str(self.text)
    
    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"

Django/django_course/blog/forms.py
from django.forms import ModelForm
from .models import Blog, Comment
from django import forms

class BlogModelForm(ModelForm):
    class Meta:
        model = Blog
        fields = ["title", "content", "image"]

    def __init__(self, *args, **kwargs):
        super(BlogModelForm, self).__init__(*args, **kwargs)
        self.fields["title"].help_text=""
        self.fields["title"].label=""
        self.fields["title"].widget=forms.Textarea(
            attrs={
                "placeholder":"Название блога",
                "rows": 1,
                "class": "form-control",
            }
        )

        self.fields["content"].help_text=""
        self.fields["content"].label=""
        self.fields["content"].widget=forms.Textarea(
            attrs={
                "placeholder":"Содержание",
                "rows": 10,
                "class": "form-control",
            }
        )

class CommentModelForm(ModelForm):
    class Meta:
        model = Comment
        fields = ["text"]

    def __init__(self, *args, **kwargs):
        super(CommentModelForm, self).__init__(*args, **kwargs)
        self.fields["text"].help_text=""
        self.fields["text"].label=""
        self.fields["text"].widget=forms.Textarea(
            attrs={
                "placeholder":"Текст комментария",
                "rows": 1,
                "class": "form-control",
            }
        )  

Django/django_course/blog/views.py
from datetime import datetime
from django.shortcuts import get_object_or_404, render, redirect
from django.core.paginator import Paginator
from .models import Blog, Comment
from .forms import BlogModelForm, CommentModelForm

def index(request):
    blogs = Blog.objects.all().order_by('-date_published')
    search = request.GET.get('search')

    if search:
        blogs = blogs.filter(title__icontains=search)

    paginator = Paginator(blogs,3)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    title = "Главная страница"
    return render(request, 'blog/blog_list.html', {'page_obj': page_obj, 'title': title})

def blog_detail(request, pk):
    blog = get_object_or_404(Blog, pk=pk)
    comments = Comment.objects.filter(blog=blog).order_by('-date_published')
    title = blog.title
    form = CommentModelForm()

    if 'post' in request.GET:
        all_blogs = Blog.objects.order_by('id')
        current_index = list(all_blogs.values_list('id', flat=True)).index(blog.id)
        
        if request.GET.get('post') == "prev":
            prev_index = current_index - 1 if current_index > 0 else len(all_blogs) - 1
            return redirect("blog:blog_detail", pk=all_blogs[prev_index].id)
        
        elif request.GET.get('post') == "next":
            next_index = current_index + 1 if current_index < len(all_blogs) - 1 else 0
            return redirect("blog:blog_detail", pk=all_blogs[next_index].id)

    context = {
        "blog": blog,
        "title": title,
        "comments": comments
    }

    if request.method == "POST":
        form = CommentModelForm(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.author = request.user
            new_comment.date_published = datetime.now()
            new_comment.blog = blog
            new_comment.save()
            return redirect("blog:blog_detail", pk=pk)
    else:
        form = CommentModelForm()
    context["form"] = form
    return render(request, 'blog/blog_detail.html', context)

def create_blog(request):
    title = "Создание блога"
    action = "Создать"
    if request.method == "POST":
        form = BlogModelForm(request.POST, request.FILES)
        if form.is_valid():
            new_blog = form.save(commit=False)
            new_blog.author = request.user
            new_blog.date_published = datetime.now()
            new_blog.save()
            return redirect("blog:index")
    else:
        form = BlogModelForm()
    return render(request, 'blog/create_update_blog.html', {'title':title, 'form':form, 'action':action})

def update_blog(request, pk):
    blog = Blog.objects.get(pk=pk)
    action = "Обновить"
    title = f"Редактирование {blog.title}"
    if request.method == "POST":
        form = BlogModelForm(request.POST, request.FILES, instance=blog)
        if form.is_valid():
            form.save()
            return redirect("blog:blog_detail",pk=pk)
    else:
        form = BlogModelForm(instance=blog)
    return render(request, 'blog/create_update_blog.html', {'title':title, 'form':form, 'action':action})

def contacts(request):
    title = "Контакты"
    return render(request, 'blog/contacts.html', {'title':title})

Django/django_course/blog/templates/blog/blog_detail.html
{% extends 'blog/layout.html' %}
{% load static %}
{% block title %}Блог{% endblock %}

{% block static %}
<link rel="stylesheet" href="{% static 'blog/css/blog_detail.css' %}">
{% endblock %}
{% block content %}
    <div class="blog_detail">
        <a class = "angle btn btn-light" href="{% url 'blog:blog_detail' pk=blog.id %}?post=prev"><i class = "fa fa-angle-left"></i></a>
        <div class="content">
            <h3 class="blog_title">{{ blog.title }}</h3>
            <img src="{{ blog.image.url }}">
            <div class = "blog_text"><a>{{ blog.content|linebreaks }}</a></div>
            <div class="blog_info">
                <a>{{blog.author}}</a>
                <a>{{blog.date_published}}</a>
            </div>    
        </div>
        <div class = "comments">
            {% if user.is_authenticated %}
                <div class="com_form">
                    <h3>Ваш комментарий</h3>
                    <form method = "POST">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="sumbit" class="btn btn-success">Отправить</button>
                    </form>
                </div>
            {% else %}
                <h3>Авторизуйтесь, чтобы оставлять комментарии</h3>
            {% endif %}
            {% if comments %}
                {% for comment in comments %}
                    <div class="comment">
                        <a><img src="{% static 'blog/img/user.png' %}"
                            style = "width: 40px; margin-right: 1px">
                            {{ comment.author }}</a>
                        <a>{{ comment.text }}</a>
                        <a style="align-self: end;">{{ comment.date_published }}</a>
                    </div>
                {% endfor %}
            {% else %}
                <a class="no_comments">Комментариев пока нет</a>
            {% endif %}
        </div>
        <a class = "angle btn btn-light" href="{% url 'blog:blog_detail' pk=blog.id %}?post=next"><i class = "fa fa-angle-right"></i></a>
    </div>
{% endblock %}

Django/django_course/blog/templates/blog/blog_list.html
{% extends 'blog/layout.html' %}
{% load static %}
{% block title %}Блог{% endblock %}

{% block static %}
<link rel="stylesheet" href="{% static 'blog/css/blog_list.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
{% endblock %}

{% block content %}
    {% if user.is_superuser %}
        <a class="btn btn-success" style="margin: 2% 0% 1% 1%;" href="{% url 'blog:create_blog' %}">
            <i class="fas fa-plus"></i> Создать блог
        </a>
    {% endif %}
    
    <form method="GET" class="search-form">
        <input type="text" name="search" placeholder="Поиск по новостям">
        <button type="submit"><i class="fas fa-search"></i> Найти</button>
    </form>
    
    <div class="news">
        {% for blog in page_obj %}
            <div class="news-card">
                <div class="news-image">
                    <img src="{{ blog.image.url }}" alt="{{ blog.title }}">
                </div>
                
                <div class="news-content">
                    <div class="news-header">
                        <h3 class="news-title">
                            <a href="{{ blog.get_absolute_url }}">{{ blog.title }}</a>
                        </h3>
                        {% if user.is_superuser %}
                            <a class="edit-btn" href="{% url 'blog:update_blog' pk=blog.id %}">
                                <i class="fas fa-pen"></i>
                            </a>
                        {% endif %}
                    </div>
                    
                    <p class="news-text">{{ blog.content|truncatechars:150 }}</p>
                    
                    <div class="news-info">
                        <span class="news-author">{{ blog.date_published }}, {{ blog.author }}</span>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    <div class="pagination">
        {% if page_obj.has_previous %}
            <a href="?page=1" class="page-link">&laquo; Первая</a>
            <a href="?page={{ page_obj.previous_page_number }}" class="page-link">Предыдущая</a>
        {% endif %}

        <span class="current-page">
            Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}" class="page-link">Следующая</a>
            <a href="?page={{ page_obj.paginator.num_pages }}" class="page-link">Последняя &raquo;</a>
        {% endif %}
    </div>
{% endblock %}

Django/django_course/blog/templates/blog/contacts.html
{% extends 'blog/layout.html' %}

{% load static %}

{% block title %}Контакты{% endblock %}

{% block static %}
<link rel="stylesheet" href="{% static 'blog/css/contacts.css' %}">
{% endblock %}

{% block content %}
<div class="contacts-container">
    <h1>Контакты</h1>
    
    <div class="contact-section">
        <h2>Обращения читателей, приём официальных писем</h2>
        <p><strong>119021 Москва, Зубовский бульвар, дом 4</strong></p>
        <p><strong>+7 (495) 645-66-01</strong> (справочная информация)</p>
        <p><strong>+7 (495) 637-45-45</strong> (факс канцелярии)</p>
        <p><strong>office@ria.ru</strong> (адрес канцелярии)</p>
    </div>
    
    <div class="contact-section">
        <h2>Редакция РИА Новости</h2>
        <p><strong>internet-group@ria.ru</strong></p>
        <p>Чтобы связаться с редакцией или сообщить обо всех замеченных ошибках,
        воспользуйтесь формой обратной связи.</p>
    </div>
    
    <div class="contact-section">
        <h2>Резюме</h2>
        <p><strong>resume@ria.ru</strong> (для соискателей вакансий РИА Новости)</p>
        <p><strong>cv@sputniknews.com</strong> (для соискателей вакансий Sputnik)</p>
    </div>
    
    <div class="contact-section">
        <h2>Коммерческие вопросы</h2>
        <p><strong>+7 (495) 645-64-05</strong></p>
        <p>Для заказа необходимого коммерческого продукта или услуги воспользуйтесь формой обратной связи</p>
    </div>
    
    <div class="contact-section">
        <h2>Пресс-служба</h2>
        <p><strong>+7 (495) 645-64-11</strong></p>
        <p><strong>media@ria.ru</strong> (медиагруппа "Россия сегодня")</p>
        <p><strong>media@sputniknews.com</strong> (Sputnik)</p>
    </div>
    
    <div class="contact-section">
        <h2>Международный мультимедийный пресс-центр "Россия сегодня"</h2>
        <p><strong>+7 (495) 645-64-72</strong></p>
        <p><strong>pressria@ria.ru</strong></p>
        <p>Подробнее о пресс-центре – на сайте <a href="https://pressria.ru" target="_blank">pressria.ru</a></p>
    </div>
    
</div>
{% endblock %}

Django/django_course/blog/templates/blog/create_update_blog.html
{% extends 'blog/layout.html' %}
{% load static %}
{% block title %}Блог{% endblock %}

{% block static %}
<link rel="stylesheet" href="{% static 'blog/css/create_update_blog.css' %}">
{% endblock %}

{% block content %}
    <div class = "createform">
        <form method="POST" enctype ="multipart/form-data">
            <div class="form">
                {% csrf_token %}
                {{ form.title }}<br>
                {{ form.content }}<br>
                {{ form.image }}<br>
                <button type="submit" class = "btn btn-success" style="margin: 10px 0 2% 0">{{ action }}</button>
            </div>
        </form>
    </div>
{% endblock %}

Django/django_course/blog/templates/blog/layout.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link   rel="stylesheet" 
            href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.2/css/bootstrap.min.css"
            integrity="sha512-b2QcS5SsA8tZodcDtGRELiGv5SaKSk1vDHDaQRda0htPYWZ6046lr3kJ5bAAQdpV2mmA/4v0wQF9MyU6/pDIAg=="
            crossorigin="anonymous" 
            referrerpolicy="no-referrer">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <link rel="stylesheet" href="{% static 'blog/css/layout.css' %}">
    <link rel="shortcut icon" href ="{% static 'blog/img/icon.png' %}">
    {% block static %}
    {% endblock %}
</head>
<body>
    <div class="header">
        <div class = "left_side">
            <a class = "btn btn-primary" href = "{% url 'blog:index' %}" >Главная страница</a>
            <a class = "btn btn-primary" href = "{% url 'blog:contacts' %}">Контакты</a>
        </div>
        <div class = "middle">
            <a><img src="/media/images/logo.png"></a>
        </div>
        <div class = "right_side">
            {% if user.is_authenticated %}
                <a>Добро пожаловать, {{user.username}} </a>
                {% if user.is_superuser%}
                    <a class = "btn btn-primary" href = "{% url 'admin:index' %}" ><i class="fa fa-cog"></i></a>
                {% endif %}
                <form class="log_out_form" action="{% url 'users:logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger"><i class="fa fa-sign-out-alt"></i>Выход</button>
                </form>
            {% else %}
                <a class = "btn btn-success" href = "{% url 'users:login' %}">Вход</a>
                <a class = "btn btn-primary" href = "{% url 'users:register' %}">Регистрация</a>
            {% endif %}
        </div>
    </div>
    <div style="height: 6%;"></div>
    {% block content %}
    {% endblock %}
</body>

</html>